### ISSUE TITLE
How have you configured scrutinizer to add gearman extension to php ?

### ISSUE THREAD

**Issue by MLKiiwy** [dominikmank/gearman#1]
Hi,

I'm working on a PHP project using gearman, and I want to use scrutinizer to analyse my project and do the code coverage and other stuffs. 
But I am blocked on my phpunit test because phpunit say in scrutinizer container we don't have the lib gearman installed/enabled. I see you have a scrutinizer analyse on your lib, my question is simple : how have you enabled/installed gearman in the scrutinizer container ?

Thanks

**Comment by dominikmank** [comment]
Hi,

the following is my scrutinizer configuration.

``` json
filter:
    excluded_paths:
        - 'tests/*'
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_code_coverage:
        enabled: true
        test_command: ./vendor/bin/phpunit
checks:
    php:
        code_rating: true
        duplication: true
build:
    dependencies:
        before:
            - sudo apt-get install -y gearman gearman-job-server libgearman-dev
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
```

The "build dependencies" does the job you want :-)

Hope this will help.

**Comment by MLKiiwy** [comment]
Yes ! You help me a lot :) 
I was trying to do a "apt-get install libgearman" before, now i have these lines : (build/dependencies/before)

``` bash
sudo apt-get install -y gearman gearman-job-server libgearman-dev
# PECL instance (Gearman Client)
wget http://pecl.php.net/get/gearman-1.1.2.tgz
tar xvfz gearman-1.1.2.tgz
cd gearman-1.1.2/
phpize
./configure
make
sudo make install
echo "extension=gearman.so" | sudo tee -a /home/scrutinizer/.phpenv/versions/5.5.25/etc/php.ini
sudo rm -f gearman-1.1.2.tgz
sudo rm -rf gearman-1.1.2/
```

With that I enabled Gearman lib in php for versions 5.5.25 on scrutinizer

Thanks

**Comment by dominikmank** [comment]
Thanks for writing it back! :-)
